### ISSUE TITLE
Dependency issue in v0.1.3

### ISSUE THREAD

**Issue by JoseGoncalves** [vyperium/mdue#3]
Using v0.1.3 in my Vue 3 app, when I execute `npm run serve` I receive the following error:
```
ERROR  Failed to compile with 1 errors                                                                                                                           

This dependency was not found:

* mdue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/AppTopbar.vue?vue&type=script&lang=js

To install it, you can run: npm install --save mdue
```

With v0.1.2 everything works fine.

**Comment by pepsighan** [comment]
Thank you for raising the issue. I have fixed up the issue with v0.1.4. Check if it works fine again.

**Comment by JoseGoncalves** [comment]
I confirm that it's working again in v0.1.4.
Tree shaking is also working fine. In my App (using 5 mdi icons), when I build for production with v0.1.2, chunk-vendors.js had 2603 KiB, but when I switched to v0.1.4, the size reduced to 180 KiB.
Thanks!

**Comment by pepsighan** [comment]
Awesome improvement. Thanks for reviewing it.
