### ISSUE TITLE
Video component name

### ISSUE THREAD

**Issue by alex-bluetrain** [vyperium/mdue#4]
how is the video icon component called? 
I've tried:

import { Video } from 'mdue';

but then if I use it in the template as `<video>` that is already an html tag
the alias for that icon is videocam, but `<videocam>` and `<video-cam>` tags doesn't seem to work.
`
error  The "Video" component has been registered but not used  vue/no-unused-components
`

am I missing something here?

EDIT: 

oh, silly me.. upper case `<Video>` works fine, I thought that was invalid.. that CamelCase was supposed to be converted to lower case with hyphens on before each uppercasing... I think Iread that somewhere in the vue docs.. aynway, it works

**Comment by pepsighan** [comment]
Since `Video` when converted to lowercase is `video` which is an existing html element, it does not refer to the icon but the video element.

So, to use it, there are two ways:
1. Use `<Video>` tag as you have used.
2. `import { Video as MVideo } from 'mdue';` and use `<m-video>`.
